[package]
name = "minecraft-jibble"
version = "0.1.0"
edition = "2021"

[dependencies]
tray-icon = "0.10"
winit = "0.28"  # Use winit 0.28 to avoid breaking changes in 0.29

[build-dependencies]
embed-resource = "2"
